// Generated by dafny2js
// Do not edit manually - regenerate from Dafny sources

import BigNumber from 'bignumber.js';

// Configure BigNumber as Dafny expects
BigNumber.config({ MODULO_MODE: BigNumber.EUCLID });

// Import the generated code as raw text
import dafnyCode from './Domain.cjs?raw';

// Set up the environment and evaluate the Dafny code
const require = (mod: string) => {
  if (mod === 'bignumber.js') return BigNumber;
  throw new Error(`Unknown module: ${mod}`);
};

// Create a function that evaluates the code with proper scope
const initDafny = new Function('require', `
  ${dafnyCode}
  return { _dafny, SwissDomain, SwissKernel, AppCore };
`);

const { _dafny, SwissDomain, SwissKernel, AppCore } = initDafny(require);

// ============================================================================
// Helpers
// ============================================================================

// deno-lint-ignore no-explicit-any
const seqToArray = (seq: any): any[] => {
  const arr = [];
  for (let i = 0; i < seq.length; i++) {
    arr.push(seq[i]);
  }
  return arr;
};

// deno-lint-ignore no-explicit-any
const toNumber = (bn: any): number => {
  if (bn && typeof bn.toNumber === 'function') {
    return bn.toNumber();
  }
  return bn;
};

// deno-lint-ignore no-explicit-any
const dafnyStringToJs = (seq: any): string => {
  if (typeof seq === 'string') return seq;
  if (seq.toVerbatimString) return seq.toVerbatimString(false);
  return Array.from(seq).join('');
};


// ============================================================================
// TypeScript Type Definitions (JSON representation)
// ============================================================================

export type Option<T> =
  | { type: 'None' }
  | { type: 'Some'; value: T };

export type Color = 'White' | 'Black';

export type Phase = 'Setup' | 'Playing' | 'Finished';

export type GameResult = 'WhiteWins' | 'BlackWins' | 'Draw';

export interface Pairing {
  whiteIdx: number;
  blackIdx: number;
}

export interface CompletedRound {
  pairings: Pairing[];
  bye: Option<number>;
  results: GameResult[];
}

export interface ActiveRound {
  pairings: Pairing[];
  bye: Option<number>;
  results: Option<GameResult>[];
}

export interface Participant {
  name: string;
  score2x: number;
  whiteCount: number;
  blackCount: number;
  colorHistory: Color[];
  byeReceived: boolean;
  opponents: number[];
}

export interface Model {
  phase: Phase;
  participants: Participant[];
  totalRounds: number;
  completedRounds: CompletedRound[];
  activeRound: Option<ActiveRound>;
}

export type Action =
  | { type: 'AddParticipant'; name: string }
  | { type: 'RemoveLastParticipant' }
  | { type: 'SetRounds'; n: number }
  | { type: 'StartTournament' }
  | { type: 'SubmitPairings'; pairings: Pairing[]; bye: Option<number> }
  | { type: 'RecordResult'; pairingIdx: number; result: GameResult }
  | { type: 'FinalizeRound' };

export interface History {
  past: Model[];
  present: Model;
  future: Model[];
}

// ============================================================================
// Dafny Runtime Types (actual Dafny runtime object shapes)
// ============================================================================

// Base Dafny runtime types
type DafnyInt = InstanceType<typeof BigNumber>;
interface DafnySeq<T = unknown> {
  readonly length: number;
  readonly [index: number]: T;
  toVerbatimString?(asLiteral: boolean): string;
  map<U>(fn: (x: T) => U): U[];
}
interface DafnySet<T = unknown> { readonly Elements: Iterable<T>; }

type DafnyOption<T> = { readonly is_None: true; readonly is_Some: false } | { readonly is_None: false; readonly is_Some: true; readonly dtor_value: T };

type DafnyColor = { readonly is_White: true; readonly is_Black: false } | { readonly is_White: false; readonly is_Black: true };

type DafnyPhase = { readonly is_Setup: true; readonly is_Playing: false; readonly is_Finished: false } | { readonly is_Setup: false; readonly is_Playing: true; readonly is_Finished: false } | { readonly is_Setup: false; readonly is_Playing: false; readonly is_Finished: true };

type DafnyGameResult = { readonly is_WhiteWins: true; readonly is_BlackWins: false; readonly is_Draw: false } | { readonly is_WhiteWins: false; readonly is_BlackWins: true; readonly is_Draw: false } | { readonly is_WhiteWins: false; readonly is_BlackWins: false; readonly is_Draw: true };

interface DafnyPairing {
  readonly is_Pairing: true;
  readonly dtor_whiteIdx: DafnyInt;
  readonly dtor_blackIdx: DafnyInt;
}

interface DafnyCompletedRound {
  readonly is_CompletedRound: true;
  readonly dtor_pairings: DafnySeq<DafnyPairing>;
  readonly dtor_bye: DafnyOption<DafnyInt>;
  readonly dtor_results: DafnySeq<DafnyGameResult>;
}

interface DafnyActiveRound {
  readonly is_ActiveRound: true;
  readonly dtor_pairings: DafnySeq<DafnyPairing>;
  readonly dtor_bye: DafnyOption<DafnyInt>;
  readonly dtor_results: DafnySeq<DafnyOption<DafnyGameResult>>;
}

interface DafnyParticipant {
  readonly is_Participant: true;
  readonly dtor_name: DafnySeq;
  readonly dtor_score2x: DafnyInt;
  readonly dtor_whiteCount: DafnyInt;
  readonly dtor_blackCount: DafnyInt;
  readonly dtor_colorHistory: DafnySeq<DafnyColor>;
  readonly dtor_byeReceived: boolean;
  readonly dtor_opponents: DafnySet<DafnyInt>;
}

interface DafnyModel {
  readonly is_Model: true;
  readonly dtor_phase: DafnyPhase;
  readonly dtor_participants: DafnySeq<DafnyParticipant>;
  readonly dtor_totalRounds: DafnyInt;
  readonly dtor_completedRounds: DafnySeq<DafnyCompletedRound>;
  readonly dtor_activeRound: DafnyOption<DafnyActiveRound>;
}

type DafnyAction = { readonly is_AddParticipant: true; readonly is_RemoveLastParticipant: false; readonly is_SetRounds: false; readonly is_StartTournament: false; readonly is_SubmitPairings: false; readonly is_RecordResult: false; readonly is_FinalizeRound: false; readonly dtor_name: DafnySeq } | { readonly is_AddParticipant: false; readonly is_RemoveLastParticipant: true; readonly is_SetRounds: false; readonly is_StartTournament: false; readonly is_SubmitPairings: false; readonly is_RecordResult: false; readonly is_FinalizeRound: false } | { readonly is_AddParticipant: false; readonly is_RemoveLastParticipant: false; readonly is_SetRounds: true; readonly is_StartTournament: false; readonly is_SubmitPairings: false; readonly is_RecordResult: false; readonly is_FinalizeRound: false; readonly dtor_n: DafnyInt } | { readonly is_AddParticipant: false; readonly is_RemoveLastParticipant: false; readonly is_SetRounds: false; readonly is_StartTournament: true; readonly is_SubmitPairings: false; readonly is_RecordResult: false; readonly is_FinalizeRound: false } | { readonly is_AddParticipant: false; readonly is_RemoveLastParticipant: false; readonly is_SetRounds: false; readonly is_StartTournament: false; readonly is_SubmitPairings: true; readonly is_RecordResult: false; readonly is_FinalizeRound: false; readonly dtor_pairings: DafnySeq<DafnyPairing>; readonly dtor_bye: DafnyOption<DafnyInt> } | { readonly is_AddParticipant: false; readonly is_RemoveLastParticipant: false; readonly is_SetRounds: false; readonly is_StartTournament: false; readonly is_SubmitPairings: false; readonly is_RecordResult: true; readonly is_FinalizeRound: false; readonly dtor_pairingIdx: DafnyInt; readonly dtor_result: DafnyGameResult } | { readonly is_AddParticipant: false; readonly is_RemoveLastParticipant: false; readonly is_SetRounds: false; readonly is_StartTournament: false; readonly is_SubmitPairings: false; readonly is_RecordResult: false; readonly is_FinalizeRound: true };

interface DafnyHistory {
  readonly is_History: true;
  readonly dtor_past: DafnySeq<DafnyModel>;
  readonly dtor_present: DafnyModel;
  readonly dtor_future: DafnySeq<DafnyModel>;
}

// ============================================================================
// Datatype Conversions
// ============================================================================

// deno-lint-ignore no-explicit-any
const optionFromJson = <T>(json: any, T_fromJson: (x: any) => T): DafnyOption<T> => {
  switch (json.type) {
    case 'None': {
      return SwissDomain.Option.create_None();
    }
    case 'Some': {
      return SwissDomain.Option.create_Some(
        T_fromJson(json.value)
      );
    }
    default:
      throw new Error(`Unknown Option type: ${json.type}`);
  }
};

// deno-lint-ignore no-explicit-any
const optionToJson = <T>(value: any, T_toJson: (x: any) => any): Option<T> => {
  if (value.is_None) {
    return { type: 'None' };
  } else if (value.is_Some) {
    return {
      type: 'Some',
      value: T_toJson(value.dtor_value)
    };
  }
  throw new Error('Unknown Option variant');
};

// deno-lint-ignore no-explicit-any
const colorFromJson = (json: any): DafnyColor => {
  switch (json) {
    case 'White':
      return SwissDomain.Color.create_White();
    case 'Black':
      return SwissDomain.Color.create_Black();
    default:
      throw new Error(`Unknown Color: ${json}`);
  }
};

// deno-lint-ignore no-explicit-any
const colorToJson = (value: any): Color => {
  if (value.is_White) {
    return 'White';
  } else if (value.is_Black) {
    return 'Black';
  }
  throw new Error('Unknown Color variant');
};

// deno-lint-ignore no-explicit-any
const phaseFromJson = (json: any): DafnyPhase => {
  switch (json) {
    case 'Setup':
      return SwissDomain.Phase.create_Setup();
    case 'Playing':
      return SwissDomain.Phase.create_Playing();
    case 'Finished':
      return SwissDomain.Phase.create_Finished();
    default:
      throw new Error(`Unknown Phase: ${json}`);
  }
};

// deno-lint-ignore no-explicit-any
const phaseToJson = (value: any): Phase => {
  if (value.is_Setup) {
    return 'Setup';
  } else if (value.is_Playing) {
    return 'Playing';
  } else if (value.is_Finished) {
    return 'Finished';
  }
  throw new Error('Unknown Phase variant');
};

// deno-lint-ignore no-explicit-any
const gameresultFromJson = (json: any): DafnyGameResult => {
  switch (json) {
    case 'WhiteWins':
      return SwissDomain.GameResult.create_WhiteWins();
    case 'BlackWins':
      return SwissDomain.GameResult.create_BlackWins();
    case 'Draw':
      return SwissDomain.GameResult.create_Draw();
    default:
      throw new Error(`Unknown GameResult: ${json}`);
  }
};

// deno-lint-ignore no-explicit-any
const gameresultToJson = (value: any): GameResult => {
  if (value.is_WhiteWins) {
    return 'WhiteWins';
  } else if (value.is_BlackWins) {
    return 'BlackWins';
  } else if (value.is_Draw) {
    return 'Draw';
  }
  throw new Error('Unknown GameResult variant');
};

// deno-lint-ignore no-explicit-any
const pairingFromJson = (json: any): DafnyPairing => {
  return SwissDomain.Pairing.create_Pairing(
    new BigNumber(json.whiteIdx),
    new BigNumber(json.blackIdx)
  );
};

// deno-lint-ignore no-explicit-any
const pairingToJson = (value: any): Pairing => {
  return {
    whiteIdx: toNumber(value.dtor_whiteIdx),
    blackIdx: toNumber(value.dtor_blackIdx)
  };
};

// deno-lint-ignore no-explicit-any
const completedroundFromJson = (json: any): DafnyCompletedRound => {
  return SwissDomain.CompletedRound.create_CompletedRound(
    _dafny.Seq.of(...(json.pairings || []).map((x: any) => pairingFromJson(x))),
    optionFromJson(json.bye, (x: any) => new BigNumber(x)),
    _dafny.Seq.of(...(json.results || []).map((x: any) => gameresultFromJson(x)))
  );
};

// deno-lint-ignore no-explicit-any
const completedroundToJson = (value: any): CompletedRound => {
  return {
    pairings: seqToArray(value.dtor_pairings).map((x: any) => pairingToJson(x)),
    bye: optionToJson(value.dtor_bye, toNumber),
    results: seqToArray(value.dtor_results).map((x: any) => gameresultToJson(x))
  };
};

// deno-lint-ignore no-explicit-any
const activeroundFromJson = (json: any): DafnyActiveRound => {
  return SwissDomain.ActiveRound.create_ActiveRound(
    _dafny.Seq.of(...(json.pairings || []).map((x: any) => pairingFromJson(x))),
    optionFromJson(json.bye, (x: any) => new BigNumber(x)),
    _dafny.Seq.of(...(json.results || []).map((x: any) => optionFromJson(x, gameresultFromJson)))
  );
};

// deno-lint-ignore no-explicit-any
const activeroundToJson = (value: any): ActiveRound => {
  return {
    pairings: seqToArray(value.dtor_pairings).map((x: any) => pairingToJson(x)),
    bye: optionToJson(value.dtor_bye, toNumber),
    results: seqToArray(value.dtor_results).map((x: any) => optionToJson(x, gameresultToJson))
  };
};

// deno-lint-ignore no-explicit-any
const participantFromJson = (json: any): DafnyParticipant => {
  return SwissDomain.Participant.create_Participant(
    _dafny.Seq.UnicodeFromString(json.name),
    new BigNumber(json.score2x),
    new BigNumber(json.whiteCount),
    new BigNumber(json.blackCount),
    _dafny.Seq.of(...(json.colorHistory || []).map((x: any) => colorFromJson(x))),
    json.byeReceived,
    _dafny.Set.fromElements(...(json.opponents || []).map((x: any) => new BigNumber(x)))
  );
};

// deno-lint-ignore no-explicit-any
const participantToJson = (value: any): Participant => {
  return {
    name: dafnyStringToJs(value.dtor_name),
    score2x: toNumber(value.dtor_score2x),
    whiteCount: toNumber(value.dtor_whiteCount),
    blackCount: toNumber(value.dtor_blackCount),
    colorHistory: seqToArray(value.dtor_colorHistory).map((x: any) => colorToJson(x)),
    byeReceived: value.dtor_byeReceived,
    opponents: Array.from(value.dtor_opponents.Elements).map((x: any) => toNumber(x))
  };
};

// deno-lint-ignore no-explicit-any
const modelFromJson = (json: any): DafnyModel => {
  return SwissDomain.Model.create_Model(
    phaseFromJson(json.phase),
    _dafny.Seq.of(...(json.participants || []).map((x: any) => participantFromJson(x))),
    new BigNumber(json.totalRounds),
    _dafny.Seq.of(...(json.completedRounds || []).map((x: any) => completedroundFromJson(x))),
    optionFromJson(json.activeRound, activeroundFromJson)
  );
};

// deno-lint-ignore no-explicit-any
const modelToJson = (value: any): Model => {
  return {
    phase: phaseToJson(value.dtor_phase),
    participants: seqToArray(value.dtor_participants).map((x: any) => participantToJson(x)),
    totalRounds: toNumber(value.dtor_totalRounds),
    completedRounds: seqToArray(value.dtor_completedRounds).map((x: any) => completedroundToJson(x)),
    activeRound: optionToJson(value.dtor_activeRound, activeroundToJson)
  };
};

// deno-lint-ignore no-explicit-any
const actionFromJson = (json: any): DafnyAction => {
  switch (json.type) {
    case 'AddParticipant': {
      return SwissDomain.Action.create_AddParticipant(
        _dafny.Seq.UnicodeFromString(json.name)
      );
    }
    case 'RemoveLastParticipant': {
      return SwissDomain.Action.create_RemoveLastParticipant();
    }
    case 'SetRounds': {
      return SwissDomain.Action.create_SetRounds(
        new BigNumber(json.n)
      );
    }
    case 'StartTournament': {
      return SwissDomain.Action.create_StartTournament();
    }
    case 'SubmitPairings': {
      return SwissDomain.Action.create_SubmitPairings(
        _dafny.Seq.of(...(json.pairings || []).map((x: any) => pairingFromJson(x))),
        optionFromJson(json.bye, (x: any) => new BigNumber(x))
      );
    }
    case 'RecordResult': {
      return SwissDomain.Action.create_RecordResult(
        new BigNumber(json.pairingIdx),
        gameresultFromJson(json.result)
      );
    }
    case 'FinalizeRound': {
      return SwissDomain.Action.create_FinalizeRound();
    }
    default:
      throw new Error(`Unknown Action type: ${json.type}`);
  }
};

// deno-lint-ignore no-explicit-any
const actionToJson = (value: any): Action => {
  if (value.is_AddParticipant) {
    return {
      type: 'AddParticipant',
      name: dafnyStringToJs(value.dtor_name)
    };
  } else if (value.is_RemoveLastParticipant) {
    return { type: 'RemoveLastParticipant' };
  } else if (value.is_SetRounds) {
    return {
      type: 'SetRounds',
      n: toNumber(value.dtor_n)
    };
  } else if (value.is_StartTournament) {
    return { type: 'StartTournament' };
  } else if (value.is_SubmitPairings) {
    return {
      type: 'SubmitPairings',
      pairings: seqToArray(value.dtor_pairings).map((x: any) => pairingToJson(x)),
      bye: optionToJson(value.dtor_bye, toNumber)
    };
  } else if (value.is_RecordResult) {
    return {
      type: 'RecordResult',
      pairingIdx: toNumber(value.dtor_pairingIdx),
      result: gameresultToJson(value.dtor_result)
    };
  } else if (value.is_FinalizeRound) {
    return { type: 'FinalizeRound' };
  }
  throw new Error('Unknown Action variant');
};

// deno-lint-ignore no-explicit-any
const historyFromJson = (json: any): DafnyHistory => {
  return SwissKernel.History.create_History(
    _dafny.Seq.of(...(json.past || []).map((x: any) => modelFromJson(x))),
    modelFromJson(json.present),
    _dafny.Seq.of(...(json.future || []).map((x: any) => modelFromJson(x)))
  );
};

// deno-lint-ignore no-explicit-any
const historyToJson = (value: any): History => {
  return {
    past: seqToArray(value.dtor_past).map((x: any) => modelToJson(x)),
    present: modelToJson(value.dtor_present),
    future: seqToArray(value.dtor_future).map((x: any) => modelToJson(x))
  };
};

// ============================================================================
// API Wrapper
// ============================================================================

interface AppInternal { _dafny: unknown; SwissDomain: unknown; SwissKernel: unknown; AppCore: unknown; }

const App = {
  // Option constructors
  None: () => SwissDomain.Option.create_None(),
  Some: (value: unknown) => SwissDomain.Option.create_Some(value),

  // Color constructors
  White: () => SwissDomain.Color.create_White(),
  Black: () => SwissDomain.Color.create_Black(),

  // Phase constructors
  Setup: () => SwissDomain.Phase.create_Setup(),
  Playing: () => SwissDomain.Phase.create_Playing(),
  Finished: () => SwissDomain.Phase.create_Finished(),

  // GameResult constructors
  WhiteWins: () => SwissDomain.GameResult.create_WhiteWins(),
  BlackWins: () => SwissDomain.GameResult.create_BlackWins(),
  Draw: () => SwissDomain.GameResult.create_Draw(),

  // Pairing constructors
  Pairing: (whiteIdx: number, blackIdx: number) => SwissDomain.Pairing.create_Pairing(new BigNumber(whiteIdx), new BigNumber(blackIdx)),

  // CompletedRound constructors
  CompletedRound: (pairings: Pairing[], bye: Option<number>, results: GameResult[]) => SwissDomain.CompletedRound.create_CompletedRound(_dafny.Seq.of(...(pairings || []).map((x: any) => pairingFromJson(x))), optionFromJson(bye, (x: any) => new BigNumber(x)), _dafny.Seq.of(...(results || []).map((x: any) => gameresultFromJson(x)))),

  // ActiveRound constructors
  ActiveRound: (pairings: Pairing[], bye: Option<number>, results: Option<GameResult>[]) => SwissDomain.ActiveRound.create_ActiveRound(_dafny.Seq.of(...(pairings || []).map((x: any) => pairingFromJson(x))), optionFromJson(bye, (x: any) => new BigNumber(x)), _dafny.Seq.of(...(results || []).map((x: any) => optionFromJson(x, gameresultFromJson)))),

  // Participant constructors
  Participant: (name: string, score2x: number, whiteCount: number, blackCount: number, colorHistory: Color[], byeReceived: boolean, opponents: number[]) => SwissDomain.Participant.create_Participant(_dafny.Seq.UnicodeFromString(name), new BigNumber(score2x), new BigNumber(whiteCount), new BigNumber(blackCount), _dafny.Seq.of(...(colorHistory || []).map((x: any) => colorFromJson(x))), byeReceived, _dafny.Set.fromElements(...(opponents || []).map((x: any) => new BigNumber(x)))),

  // Action constructors
  AddParticipant: (name: string) => SwissDomain.Action.create_AddParticipant(_dafny.Seq.UnicodeFromString(name)),
  RemoveLastParticipant: () => SwissDomain.Action.create_RemoveLastParticipant(),
  SetRounds: (n: number) => SwissDomain.Action.create_SetRounds(new BigNumber(n)),
  StartTournament: () => SwissDomain.Action.create_StartTournament(),
  SubmitPairings: (pairings: Pairing[], bye: DafnyOption<DafnyInt>) => SwissDomain.Action.create_SubmitPairings(_dafny.Seq.of(...(pairings || []).map((x: any) => pairingFromJson(x))), bye),
  RecordResult: (pairingIdx: number, result: DafnyGameResult) => SwissDomain.Action.create_RecordResult(new BigNumber(pairingIdx), result),
  FinalizeRound: () => SwissDomain.Action.create_FinalizeRound(),

  // Model accessors
  GetPhase: (m: DafnyModel) => phaseToJson(m.dtor_phase),
  GetParticipants: (m: DafnyModel) => seqToArray(m.dtor_participants).map((x: any) => participantToJson(x)),
  GetTotalRounds: (m: DafnyModel) => toNumber(m.dtor_totalRounds),
  GetCompletedRounds: (m: DafnyModel) => seqToArray(m.dtor_completedRounds).map((x: any) => completedroundToJson(x)),
  GetActiveRound: (m: DafnyModel) => optionToJson(m.dtor_activeRound, activeroundToJson),

  // AppCore functions
  Init: (): DafnyHistory => AppCore.__default.Init(),
  Dispatch: (h: DafnyHistory, a: DafnyAction): DafnyHistory => AppCore.__default.Dispatch(h, a),
  Undo: (h: DafnyHistory): DafnyHistory => AppCore.__default.Undo(h),
  Redo: (h: DafnyHistory): DafnyHistory => AppCore.__default.Redo(h),
  Present: (h: DafnyHistory): DafnyModel => AppCore.__default.Present(h),
  CanUndo: (h: DafnyHistory): boolean => AppCore.__default.CanUndo(h),
  CanRedo: (h: DafnyHistory): boolean => AppCore.__default.CanRedo(h),
  ValidPairings: (model: DafnyModel, pairings: Pairing[], bye: DafnyOption<DafnyInt>): boolean => AppCore.__default.ValidPairings(model, _dafny.Seq.of(...(pairings || []).map((x: any) => pairingFromJson(x))), bye),
  ChooseColors: (p1idx: number, p2idx: number, p1: DafnyParticipant, p2: DafnyParticipant): DafnyPairing => AppCore.__default.ChooseColors(new BigNumber(p1idx), new BigNumber(p2idx), p1, p2),
  CanStart: (model: DafnyModel): boolean => AppCore.__default.CanStart(model),
  CanSubmitPairings: (model: DafnyModel): boolean => AppCore.__default.CanSubmitPairings(model),
  CanFinalize: (model: DafnyModel): boolean => AppCore.__default.CanFinalize(model),
  CurrentRound: (model: DafnyModel): number => toNumber(AppCore.__default.CurrentRound(model)),

  // Conversion functions
  optionToJson,
  optionFromJson,
  colorToJson,
  colorFromJson,
  phaseToJson,
  phaseFromJson,
  gameresultToJson,
  gameresultFromJson,
  pairingToJson,
  pairingFromJson,
  completedroundToJson,
  completedroundFromJson,
  activeroundToJson,
  activeroundFromJson,
  participantToJson,
  participantFromJson,
  modelToJson,
  modelFromJson,
  actionToJson,
  actionFromJson,
  historyToJson,
  historyFromJson,

  // Internal modules for custom extensions
  _internal: { _dafny, SwissDomain, SwissKernel, AppCore } as AppInternal,
};

export default App;
